version: '3.5'

services:

  web:
    hostname: web
    build: .
    ports:
      - 3000:80
    restart: always
    networks:
      - net_postgres
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - net_postgres
    restart: unless-stopped

networks:
  net_postgres:
    driver: bridge

volumes:
    postgres:
