version: '3.5'

services:
  db:
    container_name: postgres_container
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  web:
    hostname: web
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    restart: always
    networks:
      - postgres
    depends_on:
      - db
    stdin_open: true
    tty: true

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
